### ISSUE TITLE
Error: using typedef-name 'sqlite3_value' after 'struct'

### ISSUE THREAD

**Issue by rstory1** [SRombauts/SQLiteCpp#133] opened 2017-08-02 13:49 UTC
I am attempting to use this project in a Qt application. I have included all the necessary files, but when I try to build my project in Qt I get this error. In addition on the same line I get a conflicting declaration 'typedef int sqlite3_value'. 

The errors occur on line 22 of Database.h

Could this be something on my end? An issue with the Qt compiler?

**Comment by SRombauts** [comment] 2017-08-02 14:55
This seems a duplicate of #125 Incompatibility in 3.19.0 and #126 several compile errors in VS 2013 (SQLite version 3.19.0)

**Comment by SRombauts** [comment] 2017-08-02 14:57
To use older SQLite version set the CMake variable SQLITE_USE_LEGACY_STRUCT (for instance "cmake . -DSQLITE_USE_LEGACY_STRUCT=ON")

**Closed by SRombauts** 2017-08-02 14:57 UTC
Labels: duplicate
