### ISSUE TITLE
several compile errors in VS 2013 (SQLite version 3.19.0)

### ISSUE THREAD

**Issue by sorinmustaca** [SRombauts/SQLiteCpp#126] opened 2017-05-24 09:19 UTC
Using the sqlite3.h and .c from the website: "C source code as an amalgamation, version 3.19.0."

Error	5	error C2352: 'SQLite::Database::check' : illegal call of non-static member function	
Error	1	error C2371: 'sqlite3_value' : redefinition; different basic types	
Error	3	error C2511: 'void SQLite::Database::createFunction(const char *,int,bool,void *,void (__cdecl *)(sqlite3_context *,int,sqlite3_value **),void (__cdecl *)(sqlite3_context *,int,sqlite3_value **),void (__cdecl *)(sqlite3_context *),void (__cdecl *)(void *))' : overloaded member function not found in 'SQLite::Database'	

Error	4	error C2597: illegal reference to non-static member 'SQLite::Database::mpSQLite'	
7	IntelliSense: no instance of overloaded function "SQLite::Database::createFunction" matches the specified type

**Comment by SRombauts** [comment] 2017-05-24 09:53
Thanks for reporting, this is a duplicate of yesterday #125 "Incompatibility in 3.19.0"

**Closed by SRombauts** 2017-05-24 09:53 UTC
