### ISSUE TITLE
Not compiling properly - help!

### ISSUE THREAD

**Issue by hintron** [SRombauts/SQLiteCpp#144] opened 2017-10-03 19:15 UTC
Hello,

I can't seem to get sqlitecpp to work with my setup. Did I miss something obvious in my usage of sqlitecpp?

## My usage:

My makefile downloads sqlitecpp, creates a build directory, cd's into it, runs `cmake ..`, runs `make`, and then copies the built sqlitecpp lib file and source header files to a local directory called `sqlitecpp` in my project. I then use those local files in my code like so:
```
#include "SQLiteCpp/SQLiteCpp.h"
#include "sqlite3.h"
``` 
And I build my program like so:
```
g++ -g Main.cpp SQLConnector.cpp -std=c++11 -I sqlitecpp -lsqlite3 -L sqlitecpp -lSQLiteCpp -o bin/Server
```
but I get the following errors:
```
In file included from sqlitecpp/SQLiteCpp/SQLiteCpp.h:23:0,
                 from SQLConnector.cpp:7:
sqlitecpp/SQLiteCpp/Database.h:22:16: error: using typedef-name ‘sqlite3_value’ after ‘struct’
 typedef struct sqlite3_value sqlite3_value;
                ^
In file included from SQLConnector.h:13:0,
                 from SQLConnector.cpp:6:
include_local/sqlite3.h:3327:20: note: ‘sqlite3_value’ has a previous declaration here
 typedef struct Mem sqlite3_value;
                    ^
In file included from sqlitecpp/SQLiteCpp/SQLiteCpp.h:23:0,
                 from SQLConnector.cpp:7:
sqlitecpp/SQLiteCpp/Database.h:22:43: error: invalid type in declaration before ‘;’ token
 typedef struct sqlite3_value sqlite3_value;
                                           ^
sqlitecpp/SQLiteCpp/Database.h:22:43: error: conflicting declaration ‘typedef int sqlite3_value’
In file included from SQLConnector.h:13:0,
                 from SQLConnector.cpp:6:
include_local/sqlite3.h:3327:20: error: ‘sqlite3_value’ has a previous declaration as ‘typedef struct Mem sqlite3_value’
 typedef struct Mem sqlite3_value;
                    ^
```

To me, it looks like there is some kind of contention with sqlite and sqlitecpp. Any ideas? I am using sqlitecpp 2.2.0 and sqlite3 v. 3.8.7.1. Any help is appreciated. Thanks!

I think this may have something to do with SQLITE_USE_LEGACY_STRUCT (see https://github.com/SRombauts/SQLiteCpp/issues/131)

**Comment by SRombauts** [comment] 2017-10-04 06:33
Exactly, you are right, you have to set this flag to ON to use an older SQLite3 library. Something like:

cd build 
cmake -DSQLITE_USE_LEGACY_STRUCT=ON - DCMAKE_BUILD_TYPE=Release ..
make

**Comment by SRombauts** [comment] 2017-10-04 06:44
This is a duplicate of the issue #125 Incompatibility in 3.19. 0 and #133

**Comment by hintron** [comment] 2017-10-04 16:27
This still doesn't work for me.

This is what I get when I instead run `cmake -DSQLITE_USE_LEGACY_STRUCT=ON -DCMAKE_BUILD_TYPE=Release ..`:

```-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake version: 3.5.1
-- CMAKE_CXX_COMPILER '/usr/bin/c++' 'GNU' '5.4.0'
-- CMAKE_CXX_FLAGS                ''
-- CMAKE_CXX_FLAGS_RELEASE        '-O3 -DNDEBUG'
-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
-- Could NOT find cppcheck
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/build
```

This looks fine, but then when I run `make`, sqlitecpp doesn't build:

```
Scanning dependencies of target SQLiteCpp
[ 11%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
In file included from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/src/Backup.cpp:16:0:
/mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/sqlite3/sqlite3.h:3784:16: error: using typedef-name ‘sqlite3_value’ after ‘struct’
 typedef struct sqlite3_value sqlite3_value;
                ^
In file included from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/include/SQLiteCpp/Backup.h:14:0,
                 from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/src/Backup.cpp:12:
/mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/include/SQLiteCpp/Database.h:25:20: note: ‘sqlite3_value’ has a previous declaration here
 typedef struct Mem sqlite3_value;
                    ^
In file included from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/src/Backup.cpp:16:0:
/mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/sqlite3/sqlite3.h:3784:30: error: conflicting declaration ‘typedef int sqlite3_value’
 typedef struct sqlite3_value sqlite3_value;
                              ^
In file included from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/include/SQLiteCpp/Backup.h:14:0,
                 from /mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/src/Backup.cpp:12:
/mnt/c/Users/hal/Documents/Oldentide/Server/sqlitecpp_temp/include/SQLiteCpp/Database.h:25:20: note: previous declaration as ‘typedef struct Mem sqlite3_value’
 typedef struct Mem sqlite3_value;
                    ^
CMakeFiles/SQLiteCpp.dir/build.make:62: recipe for target 'CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o' failed
make[2]: *** [CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SQLiteCpp.dir/all' failed
make[1]: *** [CMakeFiles/SQLiteCpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by hintron** [comment] 2017-10-04 17:04
Wait... it looks like it is building against the version of sqlite that comes with sqlitecpp... So I need to get it to build against my own version of sqlite instead somehow.

**Comment by hintron** [comment] 2017-10-04 17:09
Ok, here is the fix that seems to work:
`cmake -DSQLITE_USE_LEGACY_STRUCT=ON -DSQLITECPP_INTERNAL_SQLITE=OFF ..`
By default, the SQLITECPP_INTERNAL_SQLITE cmake var is ON, which makes it try to build off the internal sqlite package that comes with sqlitecpp instead of the sqlite in sqlitelib-dev in Ubuntu.

**Comment by hintron** [comment] 2017-10-04 19:37
Found the issue! I needed to put -lSQLiteCpp as the left-most library (see [https://stackoverflow.com/a/409402](url))
This is what it looks like now:
```g++ -g Main.cpp SQLConnector.cpp -std=c++11 -I sqlitecpp -L sqlitecpp -lSQLiteCpp -ldl -lpthread -lsqlite3 -o bin/Server -DSQLITE_USE_LEGACY_STRUCT```

**Comment by SRombauts** [comment] 2017-10-05 07:18
Thanks for the update!

For the second point, I should find a way to improve that! I am reopening the issue to track this.

**Comment by SRombauts** [comment] 2017-12-18 14:33
Well, I am closing after closer review, this since there is nothing I can do here: you need to use CMake all the way to define the variable only on CMake and everything works as expected.

Your problem is you are not using CMake so you need to define every vars by yourself on your command line.

**Closed by SRombauts** 2017-12-18 14:33 UTC
Labels: duplicate, question
